name: Docker Image CI

permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      id: build
      with: 
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }},
          ghcr.io/${{ github.repository }}:latest,
          ${{ github.repository }}:${{ github.sha }}
          ${{ github.repository }}:latest
        provenance: false
        outputs: |
          type=image,name=target,annotation-index.org/image-size=true

    - name: Echo image sizes
      shell: bash
      run: |
        echo "### Docker Image Sizes 📦" >> $GITHUB_STEP_SUMMARY
        echo "Image digest: ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Get all platforms from the manifest
        docker buildx imagetools inspect ${{ github.repository }}:${{ github.sha }} --format '{{json .}}' | \
          jq -r '.manifests[] | "#### Platform: \(.platform.os)/\(.platform.architecture)\(.platform.variant // "")\n\`\`\`\n\(.size | tonumber | ./1024/1024 | floor)MiB\n\`\`\`\n"' \
          >> $GITHUB_STEP_SUMMARY
